### ISSUE TITLE
UI for uploading datasets

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/pennai#119]
We need an interface to allow the user to upload a new dataset and specify some information about the dataset, like which field represents the 'label' column, and which fields (if any) contain categorical or ordinal data.  The backend lab server will do validation checks on the data and the UI will also need to display validation errors and warnings in an intuitive way.  The errors may be about the entire dataset (i.e. the file is unreadable), or some specific part of the data (i.e. there is a NULL value on row 3, col 5).  It may also be nice to display a preview of the data before doing the final upload.  There should be some unit tests.

New datasets are submitted to the lab server via a PUT to '/api/v1/datasets'.  See registerDatafile() method in `lab\init\loadInitialDatasets.py` for an example of it use.
Additional api calls will need to be added to the backend lab server to support validation.

---
**First pass functionality:**
Update the ui to have an *add datasets* button on the datasets page.  Clicking will navigate to a pop-up or a new page where the user can choose a file to upload and can enter the name of the 'label' column.  Submitting the request will call the existing `api/v1/datasets` api method which will either result in the dataset being uploaded successfully or an error being returned.  Basic unit tests.

**Advanced functionality** (UI flow might change to something like [user clicks *add datasets*] -> [user chooses and submits a file] -> [preview UI shows up where user can specify column info and make final submission]):
* Data preview UI before final upload
* Target field is a choice of existing columns, not a text box
* User can specify fields that contain categorical or ordinal data
* Display validation warnings and errors

**Comment by joshc0044** [comment]
dependent column dropdown - search (remove text field)
categorical feature - close icon / x icon 
ordinal feature - entire dataset 
as selecting column keys remove as options for other fields

**Comment by hjwilli** [comment]
Closing this issue.  Updates to the upload will be handled in future tickets.
