### ISSUE TITLE
guess the data types of dataset features at upload

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pennai#141]
something like https://github.com/EpistasisLab/penn-ml-benchmarks/blob/master/pmlb/write_metadata.py

would work:

```
def get_types(df):
    types=[]
    for cols in df.columns:
        if df[cols].dtype=='float64':
            types.append('continous')
        elif df[cols].dtype=='int64':
            if len(set(df[cols].values)) <= 2:
                types.append('binary')
            else:
                types.append('discrete')
return types
```

**Comment by lacava** [comment]
@joshc0044 this might be useful for the dataset upload page

**Comment by lacava** [comment]
^^^^^^^^^^^^^^ @joshc0044 ^^^^^^

**Comment by hjwilli** [comment]
@mgstauffer has implemented feature type detection in the frontend code for the dataset upload page.  Closing.
