### ISSUE TITLE
condense metafeatures.json files into one file

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pennai#175]
sad faces at all the json files I added for metafeatures of knowledgebases. compress these into a file that corresponds to a knowledge base.

**Comment by hjwilli** [comment]
- [ ] generate metafeatures csv file from data directory
- [ ] load metafeatures from csv file in addition to a collection of .json files or generation from datasources

**Comment by hjwilli** [comment]
- [ ] Update test_recommender.py to use metafeature .csv instead of .json files
