### ISSUE TITLE
Support list of integers for ordinal features during uploading dataset. 

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pennai#196]
![image](https://user-images.githubusercontent.com/21084970/57230361-31318180-6fe6-11e9-9961-02f9fe87d722.png)

As the screenshot above, when I tried to specified `[1, 3, 5, 7, 9]` for "test_ordinal_feature", the error raised **without error message.** Then I changed it to ["1", "3", "5", "7", "9"], the dataset can be loaded without error. But this string list is not working for running experiment. 

![image](https://user-images.githubusercontent.com/21084970/57230423-545c3100-6fe6-11e9-9c8f-92248a6b1f3f.png)

**Comment by hjwilli** [comment]
Using new interface.  Closing.
