### ISSUE TITLE
Dataset upload should mention accepted file types

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pennai#203]
At the moment there is no dialog to indicate to the user that .csv and .tsv files are the only ones supported. If I try to upload a txt file for example, nothing happens. We should be more clear with the supported types.

**Comment by joshc0044** [comment]
added a bit of text and a popup with a message saying unsupported file type if anything other than `csv` or `tsv` files are detected

Also, unrelated to this ticket, trying to override html file input styling is notoriously difficult, I believe one solution to create a custom styled element is to recreate one by hand which invokes a plain file input that is hidden in the browser DOM, I can change the styling of the label but the piece with the `Chose file` button and filename text are not easily changed 
![image](https://user-images.githubusercontent.com/6619927/57735075-75212800-7671-11e9-94bb-d290a4d50029.png)

**Comment by joshc0044** [comment]
solution to this issue is in main branch, closing out ticket
