### ISSUE TITLE
Train/test plot labels are cut off

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pennai#204]
![pennai_cutoff_labels](https://user-images.githubusercontent.com/6578458/57712086-fe1e6c00-763d-11e9-96ae-00737053f9f5.png)

**Comment by joshc0044** [comment]
disabling the floating labels still leaves the lines pointing to where they would be

![image](https://user-images.githubusercontent.com/6619927/57732194-874b9800-766a-11e9-9310-0e56c9215db5.png)

I'm not sure how to disable those lines. And as for styling the position of the labels, there appears to be some common minor issues with certain aspects of c3 graphs/charts getting cut off, I tried some suggestions to add padding but that did not work, I'll look into it more after the npm security issues are addressed

**Comment by hjwilli** [comment]
This was resolved.  Closing.
