### ISSUE TITLE
Push pennai docker images to DockerHub

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pennai#221]
Initially we just push pre-built production docker images to DockerHub. Later we will let DockerHub automatically build images from `Dockerfile_production` files

**Comment by weixuanfu** [comment]
Commands for push lab images to DockerHub
```shell
docker tag pennai_lab:0.13 moorelab/pennai_lab:0.13
docker push moorelab/pennai_lab:0.13
```

**Comment by hjwilli** [comment]
This works, and instructions on building and deploying PennAI production releases (including pushing images to Dockerhub) are documented here: https://github.com/EpistasisLab/pennai/blob/master/docs/guides/developerGuide.md#production-builds
