### ISSUE TITLE
Configure ml algorithm parameters for performance

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/pennai#223]
We have observed that SVC experiments using the polynomial kernel generally take the longest to run and in general, SVC is not guaranteed to converge in a reasonable time especially if the data is not scaled.  In [scikit-learn's implementation of SVC](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html) the default kernel cache size is 200MB and there is no upper limit on the number of iterations.  We should increase the kernel cache size from 200 and perhaps set max_iterations. 

In general, we want to be able to set values for algorithm parameters that should not be configurable by jobs submitted by the user or the ai (parameters like `cache_size` or `max_iterations`).

- [x] Update the algorithm configuration file in `dockers\dbmongo\files\projects.json` to include static parameter values.  Update docs in `\config\readme.md`
- [x] Update the Experiment class in `machine\learn\driver.py` to add these parameters to method_args.  Add tests.
- [x] Set the default for `cache_size` for SVC to 700

Relevant discussions:
https://github.com/scikit-learn/scikit-learn/issues/11020
https://datascience.stackexchange.com/questions/989/svm-using-scikit-learn-runs-endlessly-and-never-completes-execution

In the future, we may also consider giving the user warnings/advice about preprocessing when they are going through the UI to upload data.

**Comment by hjwilli** [comment]
updated svc entry could look like this
```
{
    "name": "SVC",
    "path": "sklearn.svm",
    "categorical_encoding_strategy": "OrdinalEncoder",
    "description": "Kernel-based classifier that maps the data into a high-dimesional space then constructs a hyperplane that maximally separates the classes in that high-dimesional space.",
    "url": "http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html",
    "static_parameters" : {"cache_size": 700, "max_iter":10000} ,
    "schema": {
        "kernel": {
            "description": "Specifies the kernel type to be used in the algorithm",
            "type": "string",
            "default": "rbf",
            "ui": {
                "style": "radio",
                "choices": ["Polynomial", "Radial basis function"],
                "values": ["poly", "rbf"]
            }
        },
...etc...

```

**Comment by weixuanfu** [comment]
The idea of `static_parameters` is great!

**Comment by weixuanfu** [comment]
![image](https://user-images.githubusercontent.com/21084970/62969220-cc52a800-bdda-11e9-91ab-dda0a0acfab4.png)
