### ISSUE TITLE
Result pages of regression problem

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pennai#230]
2 example figures:

- filename1: reg_cv_pred_[test_id].png (Note: [test_id] should be experiment ID in pennai)

![reg_cv_pred_test_id](https://user-images.githubusercontent.com/21084970/65523029-a7f9e900-deb9-11e9-972a-6e7621bd310e.png)

- filename2 : reg_cv_resi_[test_id].png
![reg_cv_resi_test_id](https://user-images.githubusercontent.com/21084970/65523031-a7f9e900-deb9-11e9-90fd-f560fbf509bb.png)

**Comment by hjwilli** [comment]
Thanks @weixuanfu, could you please include the filenames `skl_utils.py` is saving the figures as?

**Comment by weixuanfu** [comment]
Yep, I just updated the ticket.

**Comment by weixuanfu** [comment]
dtree_[test_id].png
![dtree_test_id](https://user-images.githubusercontent.com/21084970/65848782-a5621e00-e315-11e9-8373-bb05cc14af17.png)
imp_score[test_id].png
![imp_scoretest_id](https://user-images.githubusercontent.com/21084970/65848811-c4f94680-e315-11e9-8b70-75e1eabca78a.png)

**Comment by weixuanfu** [comment]
Default score is r2. And MSE and MAE are also included
Example of `value.json`

```json
{"_scores": {"train_score": 1.0, "test_score": 0.6389667197971862, 
"train_r2_score": 1.0, "r2_score": 0.6389667197971862, 
"train_neg_mean_squared_error_score": 0.0, "neg_mean_squared_error_score": -0.3722570780175796, 
"train_neg_mean_absolute_error_score": 0.0, "neg_mean_absolute_error_score": -0.3803090870583599, 
"dtree_train_score": -0.017349634065866124}}
````

Decision tree on top important features:
![dtree_test_id](https://user-images.githubusercontent.com/21084970/65930092-89708200-e3d2-11e9-809c-50a21f4b675f.png)

**Comment by weixuanfu** [comment]
- [ ] add y=x line to cross-validated predictions

**Comment by weixuanfu** [comment]
![reg_cv_pred_test_id](https://user-images.githubusercontent.com/21084970/68681648-bff0ff00-0531-11ea-80e8-6d0588645cfb.png)
![reg_cv_resi_test_id](https://user-images.githubusercontent.com/21084970/68681652-c2ebef80-0531-11ea-8129-e1c62aee5662.png)

**Comment by weixuanfu** [comment]
Ideas for presenting regression scores.

Bar chart for MSE and MAS to show the differences between train and test scores. It is noted that it can also show the difference from 0. 

![image](https://user-images.githubusercontent.com/21084970/68682967-fd568c00-0533-11ea-93c8-f07f18184aba.png)

Pie chart for presenting MSE, MAE and R2 for better showing if train scores are consistent with test scores. We may change this chart to half round.
![image](https://user-images.githubusercontent.com/21084970/68683077-2d9e2a80-0534-11ea-949a-cb34f6f48bd0.png)

**Comment by weixuanfu** [comment]
![IMG_0272](https://user-images.githubusercontent.com/21084970/68959620-5f192f00-079c-11ea-9152-d07f992840c8.jpg)

**Comment by weixuanfu** [comment]
![image](https://user-images.githubusercontent.com/21084970/69173627-22b43e80-0ace-11ea-95f7-72b1cf2c84bb.png)

![image](https://user-images.githubusercontent.com/21084970/69173633-25af2f00-0ace-11ea-9768-792f7c62a6bf.png)

**Comment by weixuanfu** [comment]
![reg_cv_resi_test_id](https://user-images.githubusercontent.com/21084970/69986573-b1cc4800-150b-11ea-8337-02e7927de355.png)

**Comment by weixuanfu** [comment]
![image](https://user-images.githubusercontent.com/21084970/71201247-9f6e4000-2267-11ea-820c-0188971410fb.png)
