### ISSUE TITLE
sklearn API for pennai

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pennai#231]
develop a sklearn-style API for PennAI that is a python package that can be run from the command line and imported like any other sklearn estimator. eventually, this package should be moved to a separate repository and imported into this one. 

relevant branch: https://github.com/EpistasisLab/pennai/tree/sklearnAPI

**Comment by weixuanfu** [comment]
About the scikit-learn API rules [Scikit-learn API](https://scikit-learn.org/stable/modules/classes.html)

**Comment by hjwilli** [comment]
This is working and has been published to PyPi:
https://pypi.org/project/pennaipy/

Related:
https://github.com/EpistasisLab/pennai/issues/253
https://github.com/EpistasisLab/pennai/issues/250
https://github.com/EpistasisLab/pennai/issues/231
https://github.com/EpistasisLab/pennai/pull/273
