### ISSUE TITLE
Possible UI improvements (uploading datasets) 

### ISSUE THREAD

**Issue by sisabelll** [EpistasisLab/pennai#232]
Here were some recommendations that I brought up during our meeting on 10/26/2019: 

- Show error message until the user moves the cursor: If the user is hovering over the message, I think it would help for the error message to stay.
- Provide a wheel? or a way to indicate that the dataset is being uploaded. When I clicked on "upload dataset," nothing happened, so I was confused if the button wasn't working or if I had done something wrong. I later realized that it was just taking time for the data set to be uploaded, so it would be helpful if there is an indicator for this. 
- Way to delete datasets? Or hide unused ones?

**Comment by hjwilli** [comment]
Implemented ui changes to support this:
- After the Upload button is clicked, the button is disabled and a loading spinner is shown until the submit call is returned
- Error message popup is no longer disabled by timeout

Closing for now.  Deleting or archiving datasets is of larger scope then UI changes and will be managed in another ticket.
