### ISSUE TITLE
evaluate efficency of knowledgebase_loader methods

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/pennai#236]
See if the methods to load knowledgebases in knowledgebase_loader.py can be made more efficient.

**Comment by lacava** [comment]
besides making knowledgebase loading more efficient, it would be nice to load a pre-trained AI at startup rather than re-training it at the beginning .

**Comment by hjwilli** [comment]
The bottleneck lines are eval-ing the dataset to transform the 'parameters' field from a string to a dictionary, and transforming the dictionary to a hashable data structure for the purposes of de-duping.

Investigate storing 'parameters' as a frozenset of tuples instead of a dictionary, as that is a hashable data structure so that only one transformation step is necessary.

https://github.com/EpistasisLab/pennai/blob/a994a6d90780586cdb84d5531814ec6df8e8e572/ai/knowledgebase_loader.py#L266-L269

https://github.com/EpistasisLab/pennai/blob/a994a6d90780586cdb84d5531814ec6df8e8e572/ai/knowledgebase_loader.py#L111

**Comment by hjwilli** [comment]
Related to https://github.com/EpistasisLab/pennai/issues/238.  Pickled knowledgebases load relatively quickly.  Closing for now.
