### ISSUE TITLE
Sorting function is not working as expected when there is a negative R2 or 0

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pennai#239]
The sorting function in experiment is not working when there is a negative R2 score. I think the bug is related to the sorting function under lab\webapp\src\data\experiments\index.js or lab\webapp\src\components\Experiments\components\ExperimentsTable\components\ExperimentsTableHeader\index.jsx

But for now I did not figure out a good fix for this UI issue.

**Comment by weixuanfu** [comment]
Hmm, the sorting function is not working for r2 score at all but works for classification problems.

**Comment by hjwilli** [comment]
The score column was sorting by the `acccuracy_score`, which is only used by classification problems.  Fixed by changing this column to sort by `exp_table_score` instead.

**Comment by weixuanfu** [comment]
Nice catch!
