### ISSUE TITLE
add ability to export/import recommender models trained on specific knowledgebases

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/pennai#241]
Add the ability to export and import recommender models that have been trained against specific knowledgebases.  This should improve the startup time when using large knowledgebases with some recommenders.

The exported models should be in pickle format and contain data that identify the recommender and knowledgebase that generated them, and the version of the code that was active when they were generated.

* add a method like generate_and_export_model() to the base recommender that takes a knowledgebase then generates a trained model saves the pickle file.  If there are recommender specific parameters that are passed to this method that change how the model is trained, these should also be saved in the pickle file.
* add a new version of load_knowledgebase() that can take a pickled model file

**Comment by lacava** [comment]
see branch https://github.com/EpistasisLab/pennai/tree/pickle_recommenders_241
TODO:
- [ ] move saved recommenders to data/recommenders/

**Comment by lacava** [comment]
- [ ] fix tests

**Comment by lacava** [comment]
todo updates:
filepath: saved_recommmender_path
filename: saved_recommender_filename

- [ ] add separate filepath and filename attributes
- [ ] if given filepath, looks for default filename in filepath
- [ ] default filepath should be './'
- [ ] change surprise recommenders to not save path 'data/recommenders'. this should be done in ai.py
- [ ] if filepath or filename is specified, try to load. otherwise do not
- [ ] add private default filename
- [ ] tests for load() and save()
- [ ] strict checking (throw error) if essential fields are different: ml_p, knowledgebase

**Comment by hjwilli** [comment]
* Nomenclature cleanup; saved_recommender => serialized_rec
* Refactored recommender class initialization parameters and behavior.  Callers of the class can now optionally specify the filename or directory that serialized recommenders will be saved/loaded from.  When initializing a recommender, it can be specified whether a serialized recommender should always be loaded, never be loaded, or loaded only if the file exists.
https://github.com/EpistasisLab/pennai/blob/7a7cb03b281fe4600c933175287ff3b0faea7235/ai/recommender/base.py#L39-L55

Additional testing still needed.

**Comment by hjwilli** [comment]
* now when pennai web app starts it will attempt to load serialized recommenders.  If serialized recommenders are not available to be loaded, they are trained fresh.
* recommender code - start private methods with "_"
* updated tests
* rename serialized svd recommenders
* TODO - current serialized SVD recommenders dont't seem to work, loading using default parameters in ai gives an error: "ValueError: the ml_p hash from the pickle is different". Verify that this version of the serialized recommender should be current.  Possibly regenerate.

---
NOTE: recommender init behavior and parameters have changed: if a kb is provided and init is not loading serialized rec, it will train the recommender using the provided kb.

updated specification:
https://github.com/EpistasisLab/pennai/blob/440c34548dc958f3e446acb4abea811e112c93f1/ai/recommender/base.py#L34-L69

**Comment by hjwilli** [comment]
This is now done, and SVD recommenders trained on PMLB are now in the repo.  (SVD takes much longer to train then the other recommenders)
