### ISSUE TITLE
Overfitting table for classification results

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/pennai#242]
Add an overfitting table similar to the one on the regression results page to the classification results page.

**Comment by weixuanfu** [comment]
I think I will add an icon on the header of each scoring metric for indicating the overfitting issue.

**Comment by weixuanfu** [comment]
Two examples below
![image](https://user-images.githubusercontent.com/21084970/74068665-3040dc80-49ca-11ea-9535-f717a3abb719.png)
![image](https://user-images.githubusercontent.com/21084970/74068695-4b135100-49ca-11ea-902b-244465aa9261.png)

**Comment by lacava** [comment]
it should be "The model *may be* overfitted!"

**Comment by weixuanfu** [comment]
OK, fixed
