### ISSUE TITLE
[Discussions] Add scikit-learn API support for ai recommenders

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pennai#250]
Based on the [`BaseRecommender`](https://github.com/EpistasisLab/pennai/blob/sklearnAPI/ai/recommender/base.py#L13) on `sklearnAPI` branch and [scikit-learn API guide](https://scikit-learn.org/stable/modules/classes.html), below is a list of ideas for adding scikit-learn support:
1. remove `update` function from `BaseRecommender` and then use it as a independent load/update knowledgebase and save knowledgebase as a pickle file (other format that can be used by `BaseRecommender` via a parameter defined in `__init__`(e.g. kb="XXX.pkl"))
2. rename `recommend` to `fit` and revise it take `X, y` from directly from dataset.
3. fit function should also fit the recommended classifiers/regessors. If multiple recommendations are provided (which can be set by another parameter e.g. `n_rec` in `__init__`, then the fit function should use `cross_eval_score` to rank those recommendations and used the one with best average CV scores for `predict` and `score` function in Recommender class
4. add predict function and score function for using best recommendation.
5. need define two classes for classification and regression respectively (for inheriting [`base.ClassifierMixin`](https://scikit-learn.org/stable/modules/generated/sklearn.base.ClassifierMixin.html#sklearn.base.ClassifierMixin) and [`base.RegressorMixin`](https://scikit-learn.org/stable/modules/generated/sklearn.base.RegressorMixin.html#sklearn.base.RegressorMixin))

**Comment by lacava** [comment]
@weixuanfu thanks for tackling this. 

1. As we discussed in our meeting, I the recommenders can mostly be left alone, and be called by a wrapper class. I think it's more useful to think of the wrapper as replacing the `AI` class. I originally made a class called `PennAI` here https://github.com/EpistasisLab/pennai/blob/sklearnAPI/ai/PennAI.py that starts out as a copy of `AI` that I thought we could change to have `fit`,`predict`, etc. methods. It also has a child class `PennAIClassifier` defined [further down](https://github.com/EpistasisLab/pennai/blob/5c50948a3c918b86135d158d947ccee94412b2b4/ai/PennAI.py#L472)
2. These would be methods in the `PennAI` class
3. I imagine fit doing this:

*fit(X,Y):*
 - initialize: train recommender or load saved recommender state
 - until stop criterion is met:
   - get recommendations for X,y
   - fit and cross validate recommended ML configs 
   - update recommender based on CV scores
 - finalize: store best model, or make ensemble of trained models that meet some performance threshold

5. I made `PennAI` inherit from BaseEstimator but your suggestions are more appropriate.

**Comment by weixuanfu** [comment]
Comparing to `AI` class, the scikit-learn wrapper need remove all API calls and getting info from configuration files (like projects.json) directly.

1. `initialize: train recommender or load saved recommender state`
- [ ] get 'ml_p' (all hyperparameters of all machine learning algorithms) information from projects directly
- [ ] load knowledgebase from plk file/json file and load meta-features if necessary (maybe import functions from `knowledgebase_loader.py`)
- [ ] add new functions to loaded saved/pickled recommenders with retraining recommenders with knowledgebase. 
    - [ ] knowledgebase hashes for matching recommender state
    - [ ] pickled trained recommenders with a hash tag of knowledgebase

2. `until stop criterion is met:`
- [ ] `stop criterion`? recommender stop providing ML methods with significant (>5%?) improvement in average CV scores   
2a.  `get recommendations for X,y`
- [ ] for recommender requiring metafeatures, pennai should generate meat-features without calling API
2b. `fit and cross validate recommended ML configs`
- [ ] run fit and CV on X,y directly without submitting jobs via API.
2c. `update recommender based on CV scores`
- [ ] update knowledgebase and metafeatures when pennai get a valid result

3. `finalize: store best model, or make ensemble of trained models that meet some performance threshold`

- [ ] output best model
- [ ] (optional) output ensemble models via [StackingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingClassifier.html) and [StackingRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingRegressor.html#sklearn.ensemble.StackingRegressor)

4. other enhancement function

- [ ] export scripts and pickle file of best model (as PennAI web UI did)
- [ ] export knowledgebase and metafeatures 
- [ ] export updated trained recommender

**Comment by hjwilli** [comment]
This is working and has been published to PyPi:
https://pypi.org/project/pennaipy/

Related:
https://github.com/EpistasisLab/pennai/issues/253
https://github.com/EpistasisLab/pennai/issues/250
https://github.com/EpistasisLab/pennai/issues/231
https://github.com/EpistasisLab/pennai/pull/273
