### ISSUE TITLE
scikit-learn wrapper for pennai recommenders

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pennai#253]
**`fit(X, y)` function**

1. `initialize: train recommender or load saved recommender state`
- [x] get 'ml_p' (all hyperparameters of all machine learning algorithms) information from projects directly (may be a python dict)
- [x] load knowledgebase from plk file/json file and load meta-features if necessary (maybe import functions from `knowledgebase_loader.py`)
- [x] add random_state
- [x] add verbose option
- [x] add new functions to loaded saved/pickled recommenders with retraining recommenders with knowledgebase. (Bill is working on this)
    - [x] knowledgebase hashes for matching recommender state
    - [x] pickled trained recommenders with a hash tag of knowledgebase

2. `until stop criterion is met:`
- [x] `stop criterion`? 
 - [x] add recommender stop providing ML methods without improvement on average CV scores in a number of iterations 
 - [x] keep n_recs for each iteration (default 10)
 - [x] add n_iters for total number of iterations (default 10)
 - [x] timeout for independent stop criterion 
2a.  `get recommendations for X,y`
- [x] for recommender requiring metafeatures, pennai should generate meat-features without calling API [code source](https://github.com/EpistasisLab/pennai/blob/master/ai/metalearning/dataset_describe.py)
2b. `fit and cross validate recommended ML configs`
- [x] run fit and CV on X,y directly without submitting jobs via API. 
2c. `update recommender based on CV scores`
- [x] update knowledgebase and metafeatures when pennai get a valid result

3. `finalize: store best model, or make ensemble of trained models that meet some performance threshold`

- [x] output best model
- [x] (optional) output ensemble models via [VotingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html) and [VotingRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingRegressor.html#sklearn.ensemble.VotingRegressor)

4. other enhancement function

- (optional) export scripts and pickle file of best model (as PennAI web UI did)
- (optional) export knowledgebase and metafeatures 
- [x] export updated trained recommender 

**predict(X) function **
- [x] use bast model from fit() to predict y_pred with X

**score(X,y) function**
- [x] using scoring function for CV in fit() to estimate score

**Others**
- [x] add unit tests
- [x] add n_jobs

**Comment by hjwilli** [comment]
This is working and has been published to PyPi:
https://pypi.org/project/pennaipy/

Related:
https://github.com/EpistasisLab/pennai/issues/253
https://github.com/EpistasisLab/pennai/issues/250
https://github.com/EpistasisLab/pennai/issues/231
https://github.com/EpistasisLab/pennai/pull/273
