### ISSUE TITLE
Render issue for Multi-class classifications

### ISSUE THREAD

**Issue by nupurbaghel** [EpistasisLab/pennai#257]
The latest release has issues rendering Multi-class classification results for experiments.
Specifically, it tries to use AUC scores which are not generated for this case. Thus, the result page cannot show up and keeps “Retrieving results”.

**Comment by nupurbaghel** [comment]
To reproduce the bug -
1. Upload an example multi-class dataset e.g. Yeast dataset from pmlb_small datasets
2. Run the Random Forest experiment (any classification one)
3. Try to view the results page for this experiment

**Comment by hjwilli** [comment]
Fixed with b2366117f20ff1790c11bd15cb999a089a246588
