### ISSUE TITLE
Update dataset upload page to be more user friendly

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/pennai#262]
Update this page to be easier to use and be more visually consistent with the rest of the website.

- [x] Add drag-and-drop functionality to the file chooser
- [x] Provide an easier way for users specify the target column and categorical/ordinal columns then a text box
- [x] For ordinal columns, provide an interface to let users specify the order of the possible field values either with some sort of drag-and-drop interface or by providing a list of values
- [x] Resolve issue with catch block and following code in FileUpload.handleSelectedFiles()
- [x] Test with very large datasets. In particular check if page is slow to load, considering new code that checks each feature for a default type.

References #119

**Comment by mgstauffer** [comment]
Closed by #298 #317 #330
