### ISSUE TITLE
add SHAP decision plot to results page

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/pennai#287]
add a decision plot for visualizing individual sample predictions broken down by feature.

**Comment by hjwilli** [comment]
Shap decision plot reference:
https://slundberg.github.io/shap/notebooks/plots/decision_plot.html

**Comment by lacava** [comment]
suggestions:

- 20 data points
- for classification, 10 samples of positive labels, 10 negative
- for classification, accuracy_rate*10 correctly classified positive and (1-accuracy_rate)*10 negatively classified samples, shown with a dotten line style ( using `misclassification` field)
- different color maps for decision plot versus summary plot
- feature_order  = `hclust' might be beneficial

**Comment by nupurbaghel** [comment]
I had a few doubts here -
- Will it be possible that we get a case where there is less than 10 example for a particular class? In case should we just select as many as we can get?
- For the case of multi-class classification, I will be assuming that examples chosen for decision plot will be different for each class. 
- Just confirming, the misclassification examples are a subset of the 20 chosen examples right?

**Comment by lacava** [comment]
> I had a few doubts here -
> 
>     * Will it be possible that we get a case where there is less than 10 example for a particular class? In case should we just select as many as we can get?

Yes. 

 
>     * For the case of multi-class classification, I will be assuming that examples chosen for decision plot will be different for each class.

I would assume so, but I haven't played with this. Let us know what you find. 

>     * Just confirming, the misclassification examples are a subset of the 20 chosen examples right?

Yes, should just be a few samples in most cases.
