### ISSUE TITLE
CI with GitHub Action/AppVeyor

### ISSUE THREAD

**Issue by weixuanfu** [EpistasisLab/pennai#303]
Alternative CI builds to travis.com

- GitHub Actions: [GitHub Actions with Docker-Compose, Node.js, and MongoDB](https://medium.com/@onufrienkos/github-actions-with-docker-compose-node-js-and-mongodb-d59bf7e20867)
- [AppVeyor](https://www.appveyor.com/docs/byoc/docker/)

**Comment by hjwilli** [comment]
Github actions CI is now active, no longer using travis.
